"""Removes lock column for payouts. Adds fee column for transactions.

Revision ID: 452e47edd813
Revises: 2b3b1f654b5
Create Date: 2014-08-14 16:58:12.009119

"""

# revision identifiers, used by Alembic.
revision = '452e47edd813'
down_revision = '2b3b1f654b5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bonus_payout', 'locked')
    op.drop_column('payout', 'locked')
    op.add_column('transaction', sa.Column('fee', sa.BigInteger(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'fee')
    op.add_column('payout', sa.Column('locked', sa.BOOLEAN(), server_default='false', nullable=True))
    op.add_column('bonus_payout', sa.Column('locked', sa.BOOLEAN(), server_default='false', nullable=True))
    ### end Alembic commands ###
